// Chakra imports
import { Box, Flex } from '@chakra-ui/react';
import Head from 'next/head';
import PropTypes from 'prop-types';
import React from 'react';
import FixedPlugin from '../../components/fixedPlugin/FixedPlugin';
import Navbar from '../../components/Navbar';

function DefaultAuth(props) {
  const {
    children,
    illustrationBackground,
    heading,
    background,
    searchString,
    setSearchString,
    placeholder
  } = props;

  return (
    <>
      <Head>
        <title>{heading}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/blue_tshirt.svg" />
      </Head>
      <Navbar
        size="full"
        heading={heading}
        background={background}
        searchString={searchString}
        setSearchString={setSearchString}
        placeholder={placeholder}
      />
      <Flex position="relative" h="max-content">
        <Flex
          h={{
            sm: 'initial',
            md: 'unset',
            lg: '100vh',
            xl: '97vh'
          }}
          w="100%"
          maxW={{ md: '66%', lg: '1313px' }}
          mx="auto"
          pt="70px"
          px={{ lg: '30px', xl: '0px' }}
          justifyContent="start"
          direction="column"
        >
          {children}
          {illustrationBackground && (
            <Box
              display={{ base: 'none', md: 'block' }}
              h="100%"
              minH="100vh"
              w={{ lg: '50vw', '2xl': '44vw' }}
              position="absolute"
              right="0px"
            >
              <Flex
                bg={`url(${illustrationBackground})`}
                justify="center"
                align="end"
                w="100%"
                h="100%"
                bgSize="cover"
                bgPosition="50%"
                position="absolute"
                borderBottomLeftRadius={{
                  lg: '120px',
                  xl: '200px'
                }}
              ></Flex>
            </Box>
          )}
        </Flex>
        <FixedPlugin />
      </Flex>
    </>
  );
}
// PROPS

DefaultAuth.propTypes = {
  illustrationBackground: PropTypes.string,
  image: PropTypes.any
};

export default DefaultAuth;
